name: Deploy Azure Functions

on:
  push:
    branches: [main]
    paths: ['functions/**']
  pull_request:
    branches: [main]
    paths: ['functions/**']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install Dependencies
      working-directory: ./functions
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      working-directory: ./functions
      run: |
        pip install pytest pytest-asyncio
        python -m pytest tests/ -v || echo "No tests found, skipping"

    - name: Build Function Package
      working-directory: ./functions
      run: |
        zip -r function-app.zip . -x "tests/*" "*.pyc" "__pycache__/*"

    - name: Deploy to Azure Functions
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
        package: './functions/function-app.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}

    - name: Health Check
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        sleep 30
        curl -f ${{ secrets.AZURE_FUNCTION_APP_URL }}/api/health || exit 1
        echo "✅ Function App deployed and healthy"
