name: Deploy Frontend

on:
  push:
    branches: [main]
    paths: ['document-intelligence-frontend/**']
  pull_request:
    branches: [main]
    paths: ['document-intelligence-frontend/**']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './document-intelligence-frontend/package-lock.json'

    - name: Install Dependencies
      working-directory: ./document-intelligence-frontend
      run: npm ci

    - name: Lint
      working-directory: ./document-intelligence-frontend
      run: npm run lint

    - name: Build
      working-directory: ./document-intelligence-frontend
      env:
        VITE_API_BASE_URL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_API_BASE_URL || secrets.DEV_API_BASE_URL }}
        VITE_APIM_SUBSCRIPTION_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PROD_APIM_SUBSCRIPTION_KEY || secrets.DEV_APIM_SUBSCRIPTION_KEY }}
      run: npm run build

    - name: Azure Login
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Static Web Apps
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "./document-intelligence-frontend"
        output_location: "dist"
        skip_app_build: true

    - name: Health Check
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        sleep 30
        curl -f ${{ secrets.FRONTEND_URL }} || exit 1
        echo "✅ Frontend deployed and accessible"
